
<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .post-id{width:2%} .post-name{ width:30%}
</style>
<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Code</th>
        <th>Balance</th>
        <th>amount_used</th>
        <th>created_from</th>
        <th>create_at</th>
        <th>Action</th>
    </tr>
    <?php
    foreach ($block->getGiftCardCollection() as $key => $giftcard){
        echo '<tr id="">
                    <td >'.$giftcard->getGiftcardId().'</td>
                    <td>'.$giftcard->getCode().'</td>
                    <td>'.$giftcard->getBalance().'</td>
                     <td>'.$giftcard->getAmountUsed().'</td>
                     <td>'.$giftcard->getCreatedFrom().'</td>
                     <td>'.$giftcard->getCreateAt().'</td>
                     <td>  <a href='.'"'.'?del='.$giftcard->getGiftcardId().'"'.'>Delete</a>
                             || <a href='.'"'.'?edit='.$giftcard->getGiftcardId().'&&balance="'.'>Edit</a>
                      </td>
                  </tr>';
    }
    ?>
</table>
<!--edit-->
<!--<h2>Edit gift card</h2> <br>-->
<!--<form id="editForm" action="" method="post">-->
<!--    <input placeholder="Code " type="text" name="code" id="">-->
<!--    <input placeholder="balance" type="text" name="balance" id="">-->
<!--</form>-->
<!--<script>-->
<!--    function edit() {-->
<!--        document.getElementById("editForm").submit();-->
<!--    }-->
<!--</script>-->
